---
HomeAutomations.Apps.StudyAutomations.StudyAutomationsConfig:
  DeskLampTriggerId: StudyDeskLamp
  SpeakerTriggerId: StudySpeakers
  Speaker: switch.study_speakers_philipp
  DeskLamp:
    Entity: light.study_desk_lamp
    SwitchAction: sensor.study_desk_lamp_switch_action
