---
HomeAutomations.Apps.StudyAutomations.StudyAutomationsConfig:
  Computers:
    #- binary_sensor.desktopphilipp
    - binary_sensor.laptopphilippenbw
  Speaker: switch.study_speakers_philipp_socket_1
  DeskLamp:
    Entity: light.study_desk_lamp
    SwitchAction: sensor.study_desk_lamp_switch_action
    Timeout: 00:05:00
    TriggerConfig:
      Entity: sensor.study_motion_detector_illuminance_lux
      MinBrightness: 0
      MaxBrightness: 200
