HomeAutomations.Apps.TrainingSchedule.TrainingScheduleConfig:
  EntityId: sensor.current_training_schedule
  MediaStatusTopic: homeautomations-client/media/status
  UpdateCrontab: 0 0 * * *
  Schedules:
    - Week: 1
      Trainings:
        - Title: Chest & Back
          Url: https://ha.pupslab.de/local/videos/P90X%2001%20-%20Chest%20&%20Back.mp4
        - Title: Plyometrics
          Url: https://ha.pupslab.de/local/videos/P90X%2002%20-%20Plyometrics.mp4
    - Week: 0
      Trainings:
        - Title: Shoulders & Arms
          Url: https://ha.pupslab.de/local/videos/P90X%2003%20-%20Shoulders%20&%20Arms.mp4
        - Title: Legs & Back
          Url: https://ha.pupslab.de/local/videos/P90X%2005%20-%20Legs%20&%20Back.mp4
