---
HomeAutomations.Apps.MovieTime.MovieTimeConfig:
  StatusTopic: homeautomations-client/media/status
  SupportedActivities:
    - Kino
  SupportedPlayers:
    - ExecutableName: chrome
    - ExecutableName: VLC
  Lights:
    - light.stehlampe
