---
HomeAutomations.Apps.Vacuum.VacuumConfig:
  Vacuum: vacuum.fantenrussel
  ReminderActiveInterval: '01:00:00'
  ReminderCrontab: 00 11 * * 1,3,5
  ResetCrontab: 00 19 * * *
  Reminder:
    Tag: vacuum
    Title: Fantenrüssel
    Template: Der Robo möchte saugen. Ist alles aufgeräumt?
    Actions:
      - Action: VACUUM_START
        Title: Saugen starten
        Destructive: false
      - Action: VACUUM_NO_START
        Title: Heute nicht
        Destructive: true
