---
HomeAutomations.Apps.MoonlightRemote.MoonlightRemoteConfig:
  ApiBaseUrl:
    Values:
      Development: https://moonlight-remote-api.pupslab.de
      Production: http://moonlight-remote-api:8080
  Pid: input_number.moonlight_pid
  CurrentHost: input_text.moonlight_current_host
  SelectedHost: input_select.moonlight_selected_host
  SelectedGame: input_select.moonlight_selected_game
  ShutdownHost: input_boolean.moonlight_shutdown_host
  ShutdownHarmony: input_boolean.moonlight_shutdown_harmony
  Features:
    Host: true
    Harmony: false
    Moonlight: true
    Bluetooth: true
  Hosts:
    - DisplayName: Desktop Philipp
      Host: 192.168.188.41
      MacAddress: 40:B0:76:DD:34:61
      Games:
        - Id: SH9
          DisplayName: "Sherlock Holmes: Chapter One"
    - DisplayName: Desktop Fabienne
      Host: 192.168.188.34
      MacAddress: AC:9E:17:EC:5F:83
      Games:
        - Id: "Overcooked All You Can Eat"
          DisplayName: "Overcooked: All You Can Eat"
        - Id: "The Witcher 3: Wild Hunt"
          DisplayName: " The Witcher 3: Wild Hunt"
  ShutdownNotification:
    Tag: moonlight
    Title: Moonlight Stream
    Template: Stream beendet. Möchtest du den Host herunterfahren?
    Service: mobile_app_iphone_philipp
    Actions:
      - Action: MOONLIGHT_SHUTDOWN
        Title: Herunterfahren
        Destructive: false
      - Action: MOONLIGHT_NO_SHUTDOWN
        Title: Nicht herunterfahren
