---
HomeAutomations.Apps.TrashReminder.TrashReminderConfig:
  PersonalCalendar: https://calendar.google.com/calendar/ical/d1c1afdj2u8m6u2b8fg09dgkhs%40group.calendar.google.com/private-2903d9f5f4dc181862f24afbb69871a9/basic.ics
  Calendar:
    BaseUrl: https://www.abfallwirtschaft-germersheim.de/online-service/abfall-termine/abfalltermine-ics-export-bis-240-liter.html
    City:
      Id: icsortschaft
      Value: Neuburg
    Types:
      Id: icsabfallart[]
      Value:
        - Bioabfall
        - Gelber Sack
        - Glasbox
        - Papier
        - Restmüll
  Sensors:
    Bioabfall: trash_bio
    Gelber Sack: trash_recycling
    Glasbox: trash_glass
    Papier: trash_paper
    Restmüll: trash_waste
