---
HomeAutomations.Apps.Vacuum.VacuumConfig:
  Vacuum: vacuum.fantenrussel
  ReminderCrontab: 00 11 * * 1,3,5
  ReminderActiveInterval: '01:00:00'
  ResetCrontab: 0 0 * * *
  Reminder:
    Tag: vacuum
    Title: Staubsauger
    Template: Der Robo möchte saugen. Ist alles aufgeräumt?
    Service: mobile_app_iphone_philipp
    Actions:
      - Action: VACUUM_START
        Title: Saugen starten
        Destructive: false
      - Action: VACUUM_NO_START
        Title: Heute nicht
        Destructive: true
