---
HomeAutomations.Apps.WallPanel.WallPanelMonitorConfig:
  OffRange:
    Min: 60
    Max: 80
  Panels:
    - Name: Hallway
      BaseTopic: wallpanel/hallway
      Switch: switch.sternen_lichterkette_socket_1
